In [1]:
import numpy as np

In [2]:
python_list = [1, 2, 3, 4, 5]
print(python_list)
print(type(python_list))

[1, 2, 3, 4, 5]
<class 'list'>


In [3]:
numpy_array = np.array(python_list)
print(numpy_array)
print(type(numpy_array))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [4]:
another_array = np.array([5,4,3,2,1])

In [5]:
print(another_array)
print(type(another_array))

[5 4 3 2 1]
<class 'numpy.ndarray'>


In [6]:
python_2d_array = [[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [11, 12, 13, 14, 15]]
print(python_2d_array)
print(type(python_2d_array))

[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [11, 12, 13, 14, 15]]
<class 'list'>


In [7]:
numpy_2d_array = np.array(python_2d_array)
print(numpy_2d_array)
print(type(numpy_2d_array))

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
<class 'numpy.ndarray'>


In [8]:
np.arange(0,15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [9]:
np.arange(0,15,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14])

In [10]:
np.arange(3,12,3)

array([3, 6, 9])

In [11]:
np.arange(3,13,3)


array([ 3,  6,  9, 12])

In [12]:
np.arange(4)

array([0, 1, 2, 3])

In [13]:
np.arange(0, 15).reshape(3, 5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [14]:
array = np.arange(0,12)
print(array)
array = array.reshape(3,4)
print(array)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [15]:
np.zeros(15)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [16]:
np.zeros(0)

array([], dtype=float64)

In [17]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [18]:
np.zeros(15).reshape(3, 5)

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [19]:
np.ones(15)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [20]:
np.ones(15).reshape(3, 5)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [21]:
np.ones(25).reshape(5, 5)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [22]:
np.ones(15, dtype=int).reshape(3, 5)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [23]:
np.zeros(15, dtype=int).reshape(3, 5)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [24]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [25]:
np.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [26]:
np.random.rand(5)

array([0.27506831, 0.53126686, 0.63878654, 0.08638232, 0.49609443])

In [27]:
np.random.rand(5)

array([0.94980326, 0.35327306, 0.70702358, 0.82109501, 0.59904839])

In [28]:
np.random.rand(3)

array([0.11171272, 0.82785325, 0.52726448])

In [29]:
np.random.rand(3)

array([0.26896723, 0.02738293, 0.86544966])

In [30]:
np.random.randint(1,100)

34

In [31]:
np.random.randint(1,100)

92

In [32]:
np.random.randint(1, 100, 15)

array([27, 69,  8, 80, 44, 76, 30, 17,  4, 12,  2, 47, 85, 92, 75])

In [33]:
np.random.randint(1, 100, 15)

array([76, 62,  7, 98, 85, 26,  9, 22, 20, 66, 73, 37, 38, 96, 18])

In [34]:
np.random.randint(1, 100, 100)

array([55,  3, 63,  4, 89, 28, 22, 49, 40, 75, 67, 34, 95, 15, 61, 70, 82,
       85, 79, 34, 29, 67, 39, 70, 63, 33, 26, 36, 98, 58, 99, 32, 14, 66,
       92, 31,  2, 11, 89, 82,  7, 36, 45, 85, 64, 67, 72,  8, 98, 34, 27,
        8, 70, 78, 61, 36, 51, 45, 59,  4, 89,  2, 57,  8, 60, 23, 65, 11,
       37, 10, 24, 87, 57, 97, 85,  7, 83, 99, 44, 52,  7, 57, 99, 73, 77,
       95, 65, 96, 63, 99,  4, 56, 84, 36, 42, 47, 31,  9, 66,  3])

In [35]:
A = np.random.randint(0, 100, 20).reshape(4, 5)
A

array([[70, 20, 77,  4, 21],
       [96, 16, 21, 68, 13],
       [53, 33, 49, 26, 36],
       [74,  1, 69, 89, 20]])

In [36]:
print(f'The smallest value in A is {A.min()}, and is a located at position {A.argmin()}')
print(f'The largest value in A is {A.max()}, and is a located at position {A.argmax()}')

The smallest value in A is 1, and is a located at position 16
The largest value in A is 96, and is a located at position 5


In [37]:
A.shape

(4, 5)

In [38]:
A = A.reshape(5,4)
A

array([[70, 20, 77,  4],
       [21, 96, 16, 21],
       [68, 13, 53, 33],
       [49, 26, 36, 74],
       [ 1, 69, 89, 20]])

In [39]:
print(f'The smallest value in A is {A.min()}, and is a located at position {A.argmin()}')
print(f'The largest value in A is {A.max()}, and is a located at position {A.argmax()}')

The smallest value in A is 1, and is a located at position 16
The largest value in A is 96, and is a located at position 5


In [40]:
np.shape(A)

(5, 4)

In [41]:
A = np.arange(1, 16)
B = np.arange(1, 30, 2)
C = np.arange(0, 4).reshape(2, 2)
D = np.arange(0, 4).reshape(2, 2)
E = np.arange(1, 16).reshape(3, 5)
F = np.arange(11)
print(f'A: {A}')
print(f'B: {B}')
print('C:')
print(C)
print('D:')
print(D)
print('E:')
print(E)
print(f'F: {F}')

A: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
B: [ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29]
C:
[[0 1]
 [2 3]]
D:
[[0 1]
 [2 3]]
E:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
F: [ 0  1  2  3  4  5  6  7  8  9 10]


In [42]:
A + B

array([ 2,  5,  8, 11, 14, 17, 20, 23, 26, 29, 32, 35, 38, 41, 44])

In [43]:
A + A

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30])

In [44]:
A + 10

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25])

In [45]:
B + 10

array([11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35, 37, 39])

In [46]:
C + D

array([[0, 2],
       [4, 6]])

In [47]:
A - B

array([  0,  -1,  -2,  -3,  -4,  -5,  -6,  -7,  -8,  -9, -10, -11, -12,
       -13, -14])

In [48]:
B - A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [49]:
-A

array([ -1,  -2,  -3,  -4,  -5,  -6,  -7,  -8,  -9, -10, -11, -12, -13,
       -14, -15])

In [50]:
A - 5

array([-4, -3, -2, -1,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [51]:
A - B - 10

array([-10, -11, -12, -13, -14, -15, -16, -17, -18, -19, -20, -21, -22,
       -23, -24])

In [52]:
A * B

array([  1,   6,  15,  28,  45,  66,  91, 120, 153, 190, 231, 276, 325,
       378, 435])

In [53]:
A * A

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144, 169,
       196, 225])

In [54]:
A * 5

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75])

In [55]:
B * -1

array([ -1,  -3,  -5,  -7,  -9, -11, -13, -15, -17, -19, -21, -23, -25,
       -27, -29])

In [56]:
-B

array([ -1,  -3,  -5,  -7,  -9, -11, -13, -15, -17, -19, -21, -23, -25,
       -27, -29])

In [57]:
A/B

array([1.        , 0.66666667, 0.6       , 0.57142857, 0.55555556,
       0.54545455, 0.53846154, 0.53333333, 0.52941176, 0.52631579,
       0.52380952, 0.52173913, 0.52      , 0.51851852, 0.51724138])

In [58]:
A/2

array([0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5,
       7. , 7.5])

In [59]:
A/B+2

array([3.        , 2.66666667, 2.6       , 2.57142857, 2.55555556,
       2.54545455, 2.53846154, 2.53333333, 2.52941176, 2.52631579,
       2.52380952, 2.52173913, 2.52      , 2.51851852, 2.51724138])

In [60]:
np.matmul(C, D)

array([[ 2,  3],
       [ 6, 11]])

In [61]:
np.sqrt(E)

array([[1.        , 1.41421356, 1.73205081, 2.        , 2.23606798],
       [2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766],
       [3.31662479, 3.46410162, 3.60555128, 3.74165739, 3.87298335]])

In [62]:
np.sqrt(A)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766,
       3.31662479, 3.46410162, 3.60555128, 3.74165739, 3.87298335])

In [63]:
np.sqrt(4)

2.0

In [64]:
np.log(E)

array([[0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791],
       [1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509],
       [2.39789527, 2.48490665, 2.56494936, 2.63905733, 2.7080502 ]])

In [65]:
np.log(B/A)

array([0.        , 0.40546511, 0.51082562, 0.55961579, 0.58778666,
       0.6061358 , 0.61903921, 0.62860866, 0.63598877, 0.64185389,
       0.64662716, 0.65058757, 0.65392647, 0.65677954, 0.65924563])

In [66]:
print(F)

[ 0  1  2  3  4  5  6  7  8  9 10]


In [67]:
np.where(F%2==0, -1, F*100)

array([ -1, 100,  -1, 300,  -1, 500,  -1, 700,  -1, 900,  -1])

In [68]:
np.where(F%2==0, F, F*100)

array([  0, 100,   2, 300,   4, 500,   6, 700,   8, 900,  10])

In [69]:
np.where(F%2==0, F+4, F*100)

array([  4, 100,   6, 300,   8, 500,  10, 700,  12, 900,  14])

In [70]:
A = np.arange(15)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [71]:
print(f'A[0]: {A[0]}')
print(f'A[5]: {A[5]}')
print(f'A[14]: {A[14]}')

A[0]: 0
A[5]: 5
A[14]: 14


In [72]:
print(f'A[0]: {A[-1]}')
print(f'A[5]: {A[-5]}')
print(f'A[14]: {A[3]*7}')

A[0]: 14
A[5]: 10
A[14]: 21


In [73]:
A[0:10]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [74]:
A[0:14]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])

In [75]:
A[0:15]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [76]:
A[0:16]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [77]:
A[0:10] = 500

In [78]:
A

array([500, 500, 500, 500, 500, 500, 500, 500, 500, 500,  10,  11,  12,
        13,  14])

In [79]:
A[0:10] = B[0:10]
A

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 10, 11, 12, 13, 14])

In [80]:
B = np.arange(50).reshape(5, 10)
B

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [81]:
print(f'0th row and 2nd col in B: {B[0, 2]}')
print(f'3rd row and 3rd col in B: {B[3, 3]}')
print(f'4th row and 2nd col in B: {B[4, 2]}')

0th row and 2nd col in B: 2
3rd row and 3rd col in B: 33
4th row and 2nd col in B: 42


In [82]:
print(f'0th row in B: {B[0]}')

0th row in B: [0 1 2 3 4 5 6 7 8 9]


In [83]:
B[0:2, 3:5]

array([[ 3,  4],
       [13, 14]])

In [84]:
B[0:2]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [85]:
B[0:2, 3:5] = -1
B

array([[ 0,  1,  2, -1, -1,  5,  6,  7,  8,  9],
       [10, 11, 12, -1, -1, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [86]:
B[0:2, 3:5] = B[0:2, 3:5] + 5
B

array([[ 0,  1,  2,  4,  4,  5,  6,  7,  8,  9],
       [10, 11, 12,  4,  4, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [87]:
C = np.arange(50).reshape(10, 5)
C

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49]])

In [88]:
C%2 == 0

array([[ True, False,  True, False,  True],
       [False,  True, False,  True, False],
       [ True, False,  True, False,  True],
       [False,  True, False,  True, False],
       [ True, False,  True, False,  True],
       [False,  True, False,  True, False],
       [ True, False,  True, False,  True],
       [False,  True, False,  True, False],
       [ True, False,  True, False,  True],
       [False,  True, False,  True, False]])

In [89]:
(C%2 == 0).sum()

25

In [90]:
C.sum()

1225

In [91]:
C[C%2 == 0]

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48])

In [92]:
C[C%2 == 0].sum()

600